create table if not exists public.event_candidates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  source_name text not null,
  post_url text not null,
  raw_content text not null,
  image_url text,
  submitted_from text,
  client_created_at timestamptz,
  review_status text not null default 'pending',
  ai_is_event boolean,
  ai_confidence numeric,
  ai_reason text,
  ai_result jsonb,
  approved_event_id bigint,
  reviewed_at timestamptz
);

alter table if exists public.event_candidates
  add column if not exists created_at timestamptz not null default timezone('utc'::text, now());

alter table if exists public.event_candidates
  add column if not exists source_name text;

alter table if exists public.event_candidates
  add column if not exists post_url text;

alter table if exists public.event_candidates
  add column if not exists raw_content text;

alter table if exists public.event_candidates
  add column if not exists image_url text;

alter table if exists public.event_candidates
  add column if not exists submitted_from text;

alter table if exists public.event_candidates
  add column if not exists client_created_at timestamptz;

alter table if exists public.event_candidates
  add column if not exists review_status text not null default 'pending';

alter table if exists public.event_candidates
  add column if not exists ai_is_event boolean;

alter table if exists public.event_candidates
  add column if not exists ai_confidence numeric;

alter table if exists public.event_candidates
  add column if not exists ai_reason text;

alter table if exists public.event_candidates
  add column if not exists ai_result jsonb;

alter table if exists public.event_candidates
  add column if not exists approved_event_id bigint;

alter table if exists public.event_candidates
  add column if not exists reviewed_at timestamptz;

create index if not exists idx_event_candidates_post_url on public.event_candidates (post_url);
create index if not exists idx_event_candidates_review_status_created_at on public.event_candidates (review_status, created_at desc);
create index if not exists idx_event_candidates_approved_event_id on public.event_candidates (approved_event_id);
