create table if not exists public.policy_consents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  user_id_hash text not null,
  policy_type text not null,
  policy_version text not null,
  consent_context text not null,
  accepted boolean not null default true,
  source text not null default 'web',
  ip_address text,
  device_info text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_policy_consents_user_id_created_at
  on public.policy_consents (user_id, created_at desc);

create index if not exists idx_policy_consents_hash_created_at
  on public.policy_consents (user_id_hash, created_at desc);

create index if not exists idx_policy_consents_policy_created_at
  on public.policy_consents (policy_type, created_at desc);

alter table public.policy_consents enable row level security;

drop policy if exists "Admins can read policy consents" on public.policy_consents;
create policy "Admins can read policy consents"
on public.policy_consents
for select
to authenticated
using (public.is_activity_log_admin());

drop policy if exists "Authenticated users can insert own policy consents" on public.policy_consents;
create policy "Authenticated users can insert own policy consents"
on public.policy_consents
for insert
to authenticated
with check (user_id is null or user_id = auth.uid());

grant all on table public.policy_consents to service_role;
grant select, insert on table public.policy_consents to authenticated;
grant usage, select on sequence public.policy_consents_id_seq to authenticated, service_role;

create or replace function public.anonymize_deleted_user_logs(
  p_user_id uuid,
  p_user_id_hash text,
  p_reason text default 'account_hard_delete'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.activity_logs
  set
    user_id = null,
    user_email = null,
    ip_address = null,
    device_info = null,
    location_guess = null,
    old_data = null,
    new_data = null,
    details = jsonb_build_object(
      'anonymized', true,
      'anonymization_reason', p_reason,
      'user_id_hash', p_user_id_hash
    ),
    metadata = coalesce(metadata, '{}'::jsonb)
      || jsonb_build_object(
        'anonymized', true,
        'anonymized_at', now(),
        'anonymization_reason', p_reason,
        'user_id_hash', p_user_id_hash
      )
  where user_id = p_user_id
     or user_email in (
       select email
       from auth.users
       where id = p_user_id
     );

  update public.policy_consents
  set
    user_id = null,
    ip_address = null,
    device_info = null,
    metadata = coalesce(metadata, '{}'::jsonb)
      || jsonb_build_object(
        'anonymized', true,
        'anonymized_at', now(),
        'anonymization_reason', p_reason
      )
  where user_id = p_user_id;
end;
$$;

grant execute on function public.anonymize_deleted_user_logs(uuid, text, text) to service_role;
