-- ============================================================
-- HUB PLANNER - Premium Subscription System
-- ============================================================

-- 1. Bảng gói Premium
CREATE TABLE IF NOT EXISTS "public"."premium_plans" (
    "id" text NOT NULL PRIMARY KEY,
    "name" text NOT NULL,
    "description" text,
    "price" integer NOT NULL DEFAULT 0, -- VND
    "duration_days" integer NOT NULL DEFAULT 30,
    "features" jsonb DEFAULT '[]'::jsonb,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."premium_plans" OWNER TO "postgres";

-- 2. Bảng đăng ký Premium của người dùng
CREATE TABLE IF NOT EXISTS "public"."user_subscriptions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "plan_id" text NOT NULL REFERENCES public.premium_plans(id),
    "status" text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'cancelled', 'pending')),
    "started_at" timestamp with time zone DEFAULT now(),
    "expires_at" timestamp with time zone NOT NULL,
    "payment_method" text, -- 'bank_transfer', 'momo', 'zalopay', 'admin_grant'
    "payment_ref" text, -- Mã giao dịch
    "amount_paid" integer DEFAULT 0,
    "auto_renew" boolean DEFAULT false,
    "cancelled_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."user_subscriptions" OWNER TO "postgres";

-- Index cho truy vấn nhanh
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_id ON public.user_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_status ON public.user_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_expires_at ON public.user_subscriptions(expires_at);

-- 3. Bảng theo dõi usage AI (rate limiting cho Free users)
CREATE TABLE IF NOT EXISTS "public"."ai_usage_daily" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "date" date NOT NULL DEFAULT CURRENT_DATE,
    "message_count" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, date)
);

ALTER TABLE "public"."ai_usage_daily" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_user_date ON public.ai_usage_daily(user_id, date);

-- 4. Bảng lịch sử thanh toán
CREATE TABLE IF NOT EXISTS "public"."payment_history" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "subscription_id" bigint REFERENCES public.user_subscriptions(id),
    "amount" integer NOT NULL,
    "method" text NOT NULL,
    "transaction_ref" text,
    "status" text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'failed', 'refunded')),
    "note" text,
    "confirmed_by" uuid, -- Admin xác nhận
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."payment_history" OWNER TO "postgres";

-- 5. Enable RLS
ALTER TABLE "public"."premium_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ai_usage_daily" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payment_history" ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies

-- premium_plans: ai cũng có thể xem
CREATE POLICY "Everyone can view active plans" ON public.premium_plans
    FOR SELECT USING (is_active = true);

CREATE POLICY "Admins can manage plans" ON public.premium_plans
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
    );

-- user_subscriptions: chỉ chủ sở hữu + admin
CREATE POLICY "Users can view own subscriptions" ON public.user_subscriptions
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Admins can manage all subscriptions" ON public.user_subscriptions
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
    );

-- ai_usage_daily: chỉ chủ sở hữu
CREATE POLICY "Users can view own usage" ON public.ai_usage_daily
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can insert own usage" ON public.ai_usage_daily
    FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own usage" ON public.ai_usage_daily
    FOR UPDATE USING (user_id = auth.uid());

-- payment_history: chỉ chủ sở hữu + admin
CREATE POLICY "Users can view own payments" ON public.payment_history
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Admins can manage all payments" ON public.payment_history
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
    );

-- 7. Seed data - Các gói mặc định
INSERT INTO public.premium_plans (id, name, description, price, duration_days, features) VALUES
    ('free', 'Miễn phí', 'Gói cơ bản cho sinh viên', 0, 0, '["Quản lý điểm số", "Xem lịch học", "Sự kiện & Lost Found", "AI Advisor (5 tin/ngày)"]'),
    ('premium_monthly', 'Premium Tháng', 'Gói nâng cao trải nghiệm', 29000, 30, '["AI Advisor không giới hạn", "Phân tích điểm nâng cao", "Xuất PDF đẹp", "Huy hiệu Premium", "Ưu tiên hỗ trợ", "Không quảng cáo"]'),
    ('premium_semester', 'Premium Học kỳ', 'Tiết kiệm 40% cho cả kỳ', 99000, 150, '["Tất cả tính năng Premium Tháng", "Tiết kiệm 40%", "Gia hạn ưu đãi"]'),
    ('premium_yearly', 'Premium Năm', 'Ưu đãi tốt nhất', 199000, 365, '["Tất cả tính năng Premium", "Tiết kiệm 55%", "Early access tính năng mới"]')
ON CONFLICT (id) DO NOTHING;

-- 8. Function kiểm tra user có Premium không (dùng trong backend)
CREATE OR REPLACE FUNCTION public.is_premium_user(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.user_subscriptions
        WHERE user_id = p_user_id
        AND status = 'active'
        AND expires_at > now()
        AND plan_id != 'free'
    );
$$;

-- 9. Function tăng usage count
CREATE OR REPLACE FUNCTION public.increment_ai_usage(p_user_id uuid)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_count integer;
BEGIN
    INSERT INTO public.ai_usage_daily (user_id, date, message_count)
    VALUES (p_user_id, CURRENT_DATE, 1)
    ON CONFLICT (user_id, date)
    DO UPDATE SET message_count = ai_usage_daily.message_count + 1;
    
    SELECT message_count INTO v_count
    FROM public.ai_usage_daily
    WHERE user_id = p_user_id AND date = CURRENT_DATE;
    
    RETURN v_count;
END;
$$;
