create table if not exists public.canva_pro_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  full_name text not null,
  student_batch text not null,
  major text not null,
  status text not null default 'pending',
  note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  constraint canva_pro_requests_status_check
    check (status in ('pending', 'approved', 'rejected', 'contacted')),
  constraint canva_pro_requests_email_check
    check (position('@' in email) > 1),
  constraint canva_pro_requests_required_fields_check
    check (
      nullif(btrim(email), '') is not null
      and nullif(btrim(full_name), '') is not null
      and nullif(btrim(student_batch), '') is not null
      and nullif(btrim(major), '') is not null
    )
);

create index if not exists canva_pro_requests_status_created_at_idx
  on public.canva_pro_requests (status, created_at desc);

create index if not exists canva_pro_requests_user_id_idx
  on public.canva_pro_requests (user_id);

create or replace function public.set_canva_pro_requests_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  if new.status is distinct from old.status and new.status in ('approved', 'rejected', 'contacted') then
    new.reviewed_at = coalesce(new.reviewed_at, now());
    new.reviewed_by = coalesce(new.reviewed_by, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_canva_pro_requests_updated_at on public.canva_pro_requests;
create trigger trg_canva_pro_requests_updated_at
before update on public.canva_pro_requests
for each row execute function public.set_canva_pro_requests_updated_at();

alter table public.canva_pro_requests enable row level security;

drop policy if exists "canva_pro_requests_insert_public_pending" on public.canva_pro_requests;
create policy "canva_pro_requests_insert_public_pending"
on public.canva_pro_requests
for insert
to anon, authenticated
with check (
  coalesce(status, 'pending'::text) = 'pending'::text
  and nullif(btrim(email), '') is not null
  and position('@' in email) > 1
  and nullif(btrim(full_name), '') is not null
  and nullif(btrim(student_batch), '') is not null
  and nullif(btrim(major), '') is not null
  and (user_id is null or user_id = (select auth.uid()))
);

drop policy if exists "canva_pro_requests_select_staff" on public.canva_pro_requests;
create policy "canva_pro_requests_select_staff"
on public.canva_pro_requests
for select
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where (ur.id = (select auth.uid()) or ur.user_id = (select auth.uid()))
      and ur.role in ('admin', 'auditor', 'ctv')
  )
);

drop policy if exists "canva_pro_requests_update_staff" on public.canva_pro_requests;
create policy "canva_pro_requests_update_staff"
on public.canva_pro_requests
for update
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where (ur.id = (select auth.uid()) or ur.user_id = (select auth.uid()))
      and ur.role in ('admin', 'auditor', 'ctv')
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    where (ur.id = (select auth.uid()) or ur.user_id = (select auth.uid()))
      and ur.role in ('admin', 'auditor', 'ctv')
  )
);

drop policy if exists "canva_pro_requests_delete_staff" on public.canva_pro_requests;
create policy "canva_pro_requests_delete_staff"
on public.canva_pro_requests
for delete
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where (ur.id = (select auth.uid()) or ur.user_id = (select auth.uid()))
      and ur.role in ('admin', 'auditor', 'ctv')
  )
);

grant all on table public.canva_pro_requests to anon, authenticated, service_role;
grant all on sequence public.canva_pro_requests_id_seq to anon, authenticated, service_role;
